site_name: numbapy
repo_url: https://github.com/filbet4/numbapyproject
nav:
  - Home: index.md
  - API: api.md
theme:
  name: material
markdown_extensions:
  - admonition
  - toc:
      permalink: true
